version: '3.8'

services:
  mindclash:
    container_name: mindclash
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      coolify:
        aliases:
          - mindclash

networks:
  coolify:
    external: true
